name: miraswiftdemo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_database: ^11.3.9
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.4
  http: ^1.4.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  webview_flutter: ^4.13.0
  accordion: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
