name: miraswift_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/miraswift_transparent.png
